### ISSUE TITLE
connection details to idr omero

### ISSUE THREAD

**Issue by sunyi000** [idr-contrib/community#24]
Hi,

I'm trying to download images from idr repository using idr-py. 

I have received an error connecting to omero

"No host specified. Use omero.client(HOSTNAME), ICE_CONFIG, or similar."

What are the connection details such as HOSTNAME, USERNAME for connecting to the omero DB?

Thanks very much
Yi 

@beatrizserrano

**Comment by manics** [comment]
Install the idr-py module (`pip install idr-py)`. Then you can connect:
```python
from idr import connection
conn = connection('idr.openmicroscopy.org', 'public', 'public')
...
conn.close()
```
Note this is different from the default OMERO.py connection methods as it includes load-balancing.

**Comment by sunyi000** [comment]
Thanks Simon, 

I have installed omero-py, matplotlib, pandas, requests and idr-py

zero-ice seems to be a dependency of omero-py which is installed automatically during omero-py installation

I'm still getting errors saying "cannot import name connection". 
Did I miss anything here? 

The same piece of code runs ok in idr public jupyter server

Thanks very much

**Comment by manics** [comment]
Does `import idr` work?

What Python version are you using? If it's Python 3 can you try `pip install idr-py==0.4.0.dev3 omero-py==5.6.dev8`?

**Comment by sunyi000** [comment]
import idr works.

python version is 2.7

**Comment by manics** [comment]
Can you try:
```python
import idr
conn = idr.connections.connection('idr.openmicroscopy.org', 'public', 'public')
```

**Comment by sunyi000** [comment]
Hi Simon,

it seems to be working for me now.

I still need to test my script, but now the connection succeeded.

I tried a fresh install of everything, but this time instead of using conda install, I used pip to install every single dependency.

Just another question, on the idr-py page in pypi, it says omero-py 5.4.X is required, but it seems to work with 5.5 as well.

Thanks very much

**Comment by sunyi000** [comment]
Hi Simon,
just an update, it all works for me, I can download images from idr now.

Thanks v much

**Comment by manics** [comment]
That's great, thanks for letting us know.
